admin:
  port: 8081
  enabled: true
clusters:
  - name: "path-cluster"
    policy: "round_robin"
    endpoints:
      - name: "test-endpoint"
        address: "0.0.0.0"
        protocol: "http"
        port: 8082
  - name: "source_ip-cluster"
    policy: "round_robin"
    endpoints:
      - name: "test-endpoint"
        address: "0.0.0.0"
        protocol: "http"
        port: 8083
listeners:
  name: "test-listener"
  port: 8080
  type: "http"
  tls: true
  certPath: "./certs/cert.pem"
  keyPath: "./certs/key.pem"
  listening: true
  filter:
    name: "test-filter"
    rules:
      - name: "source_ip-rule"
        type: "source_ip"
        value: "127.0.0.1"
        action: "allow"
        enabled: true
        cluster: "source_ip-cluster"
      - name: "path-rule"
        type: "path"
        value: "/"
        action: "allow"
        enabled: true
        cluster: "path-cluster"
