admin:
  port: 8081
  enabled: true
clusters:
  - name: "default-cluster"
    policy: "round_robin"
    endpoints:
      - name: "test-endpoint"
        address: "0.0.0.0"
        protocol: "http"
        port: 8082
      - name: "test-endpoint-2"
        address: "0.0.0.0"
        protocol: "http"
        port: 8083
listeners:
  name: "test-listener"
  port: 8080
  type: "http"
  tls: true
  certPath: "./certs/cert.pem"
  keyPath: "./certs/key.pem"
  listening: true
  filter:
    name: "test-filter"
    rules:
      - name: "default-rule"
        type: "path"
        value: "/"
        action: "allow"
        enabled: true
        cluster: "default-cluster"
