admin:
  port: 8081
  enabled: true
clusters:
  - name: "path-cluster"
    policy: "round_robin"
    endpoints:
      - name: "test-endpoint"
        address: "0.0.0.0"
        protocol: "http"
        port: 8082
listeners:
  name: "test-listener"
  port: 8080
  type: "http"
  tls: false
  certPath: "./certs/cert.pem"
  keyPath: "./certs/key.pem"
  listening: true
  filter:
    name: "test-filter"
    rules:
      - name: "path-rule"
        type: "host"
        value: "/"
        action: "forward"
        enabled: true
        cluster: "path-cluster"
