admin:
  port: 8081
  enabled: true
clusters:
  - name: "path-cluster"
    policy: "round_robin"
    endpoints:
      - name: "test-endpoint"
        address: "0.0.0.0"
        port: 8082
  - name: "header-cluster"
    policy: "round_robin"
    endpoints:
      - name: "test-endpoint"
        address: "0.0.0.0"
        port: 8083
listeners:
  name: "test-listener"
  port: 8080
  type: "http"
  listening: true
  filter:
    name: "test-filter"
    rules:
      - name: "path-rule"
        type: "path"
        value: "/"
        action: "allow"
        enabled: true
        cluster: "path-cluster"
      - name: "header-rule"
        type: "header"
        key: "X-Test-Header"
        value: "test-value"
        action: "allow"
        enabled: true
        cluster: "header-cluster"
